version: '3.8'

services:
  postgres:
    image: postgres
    restart: always
    ports: 
      - "5432:5432"
    environment:
      - POSTGRES_HOST=127.0.0.1
      - POSTGRES_USER=useradmin
      - POSTGRES_PASSWORD=pass123
      - POSTGRES_DB=experimental_db